### ISSUE TITLE
Plone 6 page overhaul

### ISSUE THREAD

**Issue by tisto** [plone/plone.de#19]
We should translate the 

https://plone.org/news-and-events/news/2022/plone-6-0-released

and add the content to:

https://plone.de/nachrichten/plone-6-ist-da

We also need a Plone 6 page like:

https://plone.org/why-plone/plone-6

**Comment by jonaspiterek** [comment]
Updated content to: 
https://plone.de/nachrichten/plone-6-ist-da/

Also we have a Plone 6 page:
https://plone.de/warum-plone/plone-6
