### ISSUE TITLE
Plone Tagung

### ISSUE THREAD

**Issue by tisto** [plone/plone.de#33]
We should add the Plone Tagung prominently on plone.de. cc @MrTango

**Comment by MrTango** [comment]
good idea, i just opened the ticket shop today. would be good to do this tomorrow.

**Comment by MrTango** [comment]
@tisto can you please give me the permissions to publish news.

**Comment by tisto** [comment]
@MrTango did you login to the site already? What's your username?

**Comment by tisto** [comment]
@MrTango I can not find your username. Please go to https://plone.de/login and login via github. I will give you access as soon as I can see your account on plone.de.

I'd suggest that we add a news item and put the Plone Tagung as the first slide on our slider on the plone.de front page.

**Comment by tisto** [comment]
@MrTango I granted you admin permissions. I did not find your account before because I searched for "MrTango" and not "Maik" :)
