### ISSUE TITLE
please reactivate my former editor account

### ISSUE THREAD

**Issue by acsr** [plone/plone.de#34]
Hi all,
thanks to the relaunch team for the current Plone6 based Plone.de preserving lots of the history of the german Community milestones over the years. Unfortunately I discovered broken links, images are missing and some typos or encoding migration issues.

If you can grant me the necessary edit rights, I can touch up those and add existing images / matching keyvisuals from my archive and can promise proper work.

Blocker: My former classic credentials are not working anymore, but I have already created a new user under my github credentials. Feel free to escalate privileges of my account or reactivate my acsr user if still available (to keep authorship if preserved for older stuff).

I am happy if you drop me a line and I can start to add further conributions.
You can completely remove this ticket from the tracker later.

Cu maybe in Gießen

Armin

**Comment by tisto** [comment]
@acsr hey Armin, thanks for offering your help! This is highly appreciated. Please go to plone.de/login and log in with your github account. As soon as you do this I can grant you permissions on the site.

**Comment by tisto** [comment]
@acsr I granted you admin permissions on plone.de. Go ahead!
