### ISSUE TITLE
Move to Volto Light Theme?

### ISSUE THREAD

**Issue by tisto** [plone/plone.de#35]
@fredvd @jonaspiterek @Molochem @ericof @sneridagh @jackahl we currently use a custom theme for plone.de, which will require some work in the next few years to keep it up-to-date. I was wondering if it wouldn't be better to move to Volto Light Theme and use a minimal layer of customizations on top of this (upload a custom logo, use custom colors, use a custom footer). This will make it easier for us to maintain the site in the years to come and we also contribute to Open Source when we fix things on plone.org.

@ericof @fredvd what are the plans for the regional Plone sites (BR, etc.) and plone.org in the long run?

**Comment by fredvd** [comment]
I'm all for upgrading the custom plone.de theme to Volto Light Theme. And use the experience we gain with to upgrade plone.org later this year. 

background: 

Last year I wanted to use  an existing site/theme for a 'quick' restart of plone.nl/benelux and first copied 2023.ploneconf.org in february/march. Then I learned about the plone.de update effort and helped with that at the beethoven sprint, also with the idea to re-use the plone.de theme for plone.nl.  And then I ran out of volunteer time myself with more pressing priorities and health issues.  If plone.de is upgraded to use vlt, I can use that as 1:1 setup copy again for plone.nl.

A site specific volto theme developed top of plain 'core' Volto that can handle all core Plone content types and functionality will become very specific for that one site and take more and more effort to maintain as you add some blocks and functionality over time. Let alone reuse the same base theme on multiple sites.
 
That's not a problem for large sites where the customisations pay of for an organisation and are worth the investments, (feedback on theming Plone in the past was that even if you theme a site it looks to much like 'Plone': but the Plone Community lacks both volunteers and resources to afford the maintenance costs. And we actually WANT our regional Plone sites to look similar like Plone (plone.org).

Another argument is that even though I'm no a frontender to me it seems a lot of cool frontend technology like css grid, container queries and other improvements are finally fully usable and most new website projecst want to use these best practices. Or best/quickest option at the moment is to use those with Volto is a base theme like VLT that is enabled for that tech.

@ericof  The ploneconf.org website, is VLT also considered there?

**Comment by tisto** [comment]
@fredvd I am pretty sure ploneconf.org is a VLT site already. :)

**Comment by fredvd** [comment]
> @fredvd I am pretty sure ploneconf.org is a VLT site already. :)

Yes, you're right, I was still thinking in 2023 when I wrote that summary, 2023.ploneconf.org was built by Code Syntax with a new custom theme.

**Comment by fredvd** [comment]
Let's close this, there's already a  version of VLT on testing.plone.de and now we have to polish it a bit to get it ready
