### ISSUE TITLE
Redirect http://demo.plone.de/de/demo to https://demo.plone.org/

### ISSUE THREAD

**Issue by tisto** [plone/plone.de#4]
There is a German blogpost that features http://demo.plone.de:

https://www.ionos.de/digitalguide/hosting/cms/plone-das-barrierefreie-cms-im-ueberblick/

Maybe we should add a redirect to demo.plone.org to keep the link alive. cc @fredvd @ericof

**Comment by jonaspiterek** [comment]
demo.plone.de redirects to demo.plone.org
