### ISSUE TITLE
plone.de is laggy and not responsive on [[20240213]] 22:00 CET and later

### ISSUE THREAD

**Issue by acsr** [plone/plone.de#45]
Steps to reproduce:

1. visit the homepage https://plone.de
2. Click on Services in the Navigation
3. wait (gähn)

**Comment by acsr** [comment]
I am on Telekom Business DSL 100

**Comment by acsr** [comment]
everything back to normal now at 20240214_002344-CET

**Comment by acsr** [comment]
I am sorry – since yesterday evening I still recognize stalling while loading https://plone.de/ leading to heavy warnings and time out on mobile and desktop, over landline and via LTE as well. Reopen the ticket now. Experiences from other locations welcome.

**Comment by acsr** [comment]
This is screenshot from  yesterday from an iPhone
![IMG_6463](https://github.com/plone/plone.de/assets/400035/df44365c-0fbd-4caa-9176-87ef88208cfb)

**Comment by fredvd** [comment]
@acsr @ericof  and others already checked the site last week when something similar happened (I think) and they couldn't find a direct cause

**Comment by stevepiercy** [comment]
Performance is excellent from Eugene, Oregon, US, on 1Gb fiber, except for the freaking huge images.

**Comment by MrTango** [comment]
@tisto @jackahl please have a look or ping who ever in change of the content.

**Comment by acsr** [comment]
@tisto @jackahl If you look in the logs, my IP was 87.128.58.195 during desktop access.

**Comment by fredvd** [comment]
We are planning to add application monitoring to all plone foundation websites. with this we can monitor the response and process time of every requests and spikes like these should become visible. 

@acsr I rememers seeing a more recent message from you 1 or 2 weeks ago, but I can't remember on which platform. Anyway:  I checked the site right away and for me plone.de was snappy and very responsive.   Also we have uptime kuma checking the sites and I only 2 warnings in the last 30 days where the site has been briefly unavailable. 

So I'm afraid we won't get to the bottom of this until we have application monitoring (tracing) in place, but this might take a while still, depending on volunteers.

**Comment by acsr** [comment]
I can confirm, that plone.de is now snappy for me as well. Hard to tell, why this comes up from time to time. Other sites were OK when I wrote my ticket. Lets see if it comes back again.
