### ISSUE TITLE
Use logos block for front page and agency subpage

### ISSUE THREAD

**Issue by tisto** [plone/plone.de#55]
# Use logos block for

- front page: https://plone.de
- plone agencies: https://plone.de/services/plone-agentur

@jonaspiterek can you look into this please?

**Comment by jonaspiterek** [comment]
I tested the logos block. There was a problem with the image widths (see image below). Fixed with #56.

![image](https://github.com/plone/plone.de/assets/110389276/3ae552eb-3b53-4262-9533-2ab65fdc3744)

**Comment by jonaspiterek** [comment]
@tisto we are now using the logos block for
- front page: https://plone.de
- plone agencies: https://plone.de/services/plone-agentur
