### ISSUE TITLE
Changes for "Plone Agenturen"

### ISSUE THREAD

**Issue by petschki** [plone/plone.de#61]
See https://plone.de/services/plone-agentur

- Kombinat -> **Götzis**, Österreich
- Webmeisterei -> Feldkirch, **Österreich**
- programmatic -> Graz, **Österreich**

Thank you!

**Comment by jonaspiterek** [comment]
@petschki Thanks for the pointer! I've updated the Plone agencies site. Please take a look and confirm: https://plone.de/services/plone-agentur

**Comment by petschki** [comment]
Thanks!
